/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s
and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input: s = "abcd" t = "abcde"
Output: e
Explanation: 'e' is the letter that was added.
 */
import java.util.*;
public class FindTheDiff {
    public static char findTheDifference(String s, String t) {

        HashMap<Character,Integer> map = new HashMap<>();

        Stack<Character> stack = new Stack<>();

        for (int i = 0 ; i < t.length();i++){
            stack.push(t.charAt(i));
        }
        for (int i = 0 ; i < s.length();i++){

            int value = 0 ;

            if(map.get(s.charAt(i))==null){
                value = 1;

            }
            else {
                value=map.get(s.charAt(i)) + 1 ;
            }

            map.put(s.charAt(i),value);
        }

        char ch ;

        while (stack.size()>1){
            ch = stack.pop();
            if(map.containsKey(ch)){

                if (map.get(ch) > 1) {
                    map.put(ch,map.get(ch)-1);
                }
                else {
                    map.remove(ch);
                }
            }
            else {
                return ch;
            }
        }


        ch = stack.get(0);
        return ch;
    }
    public static void main(String[] args) {
       String s = "abcd";
       String t = "abcde";

        System.out.println( findTheDifference(s,t));
    }
}